#to run from root: execute in Terminal docker-compose -f docker/docker-compose.yml up --build -d
services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: photobookcontainer
    ports:
      - "8080:8080"       # api endpoint
      - "5005:5005"       # <— expose debug port to host

    depends_on:
      mongoDB:
        condition: service_healthy
    secrets:
      - MONGO_URI_FILE
      - ENCRYPTION_KEY_FILE
    environment:
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
      # Instead of hardcoding values, point to secret file paths
      MONGO_URI_FILE: /run/secrets/MONGO_URI_FILE
      ENCRYPTION_KEY_FILE: /run/secrets/ENCRYPTION_KEY_FILE

  mongoDB:
    image: mongo:5
    restart: always
    environment:
      TZ: "Europe/Berlin"
      MONGO_INITDB_ROOT_USERNAME: photobook_backend
      MONGO_INITDB_ROOT_PASSWORD: photobook_backend
      MONGO_INITDB_DATABASE: photobook

    # for local development (ich musste 27018 freigeben, weil auf arbeitsrechener 27017 belegt ist)
    container_name: mongoDB
    ports:
      - "27018:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"] #Runs a JavaScript snippet in the Mongo shell. returns ok if the ping ist erfolgreich
      interval: 30s
      timeout: 5s
      retries: 6

  #access mongo db docker container:
  #docker exec -it mongoDB bash
  #mongosh "mongodb://snake_backend:snakesLikeToHisss222@mongoDB:27017/snake_userData?authSource=admin"
  #show collections
  #find all documents:
  #db.users.find({}, { _id: 1 })
  # to see the mail too: db.users.find({}, { _id: 1 , mail: 1})
  #delete specific document via id:  db.users.deleteOne({ _id: ObjectId("692990015d9c7365c72d495b") });

secrets:
  MONGO_URI_FILE:
    file: ../backend/src/main/resources/uri.txt
  ENCRYPTION_KEY_FILE:
    file: ../backend/src/main/resources/encryption.txt
